FileVersion = 1

[Project]
Name = "Beef-Net"
TargetType = "BeefLib"
StartupObject = "Beef_Net.Program"

[Configs.Debug.Win32]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/OpenSSL/Win32/bin/*.dll\")"]

[Configs.Debug.Win64]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/OpenSSL/Win64/bin/*.dll\")"]

[Configs.Debug.Linux64]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/OpenSSL/Lin64/lib/*.so.*\")"]

[Configs.Release.Win32]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/OpenSSL/Win32/bin/*.dll\")"]

[Configs.Release.Win64]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/OpenSSL/Win64/bin/*.dll\")"]

[Configs.Release.Linux64]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/OpenSSL/Lin64/lib/*.so.*\")"]

[Configs.Paranoid.Win32]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/OpenSSL/Win32/bin/*.dll\")"]

[Configs.Paranoid.Win64]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/OpenSSL/Win64/bin/*.dll\")"]

[Configs.Paranoid.Linux64]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/OpenSSL/Lin64/lib/*.so.*\")"]

[Configs.Test.Win32]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/OpenSSL/Win32/bin/*.dll\")"]

[Configs.Test.Win64]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/OpenSSL/Win64/bin/*.dll\")"]

[Configs.Test.Linux64]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/OpenSSL/Lin64/lib/*.so.*\")"]
