FileVersion = 1
Dependencies = {corlib = "*", Beef-Net = "*", corlib = "*"}

[Project]
Name = "Beef-Net-Test"
StartupObject = "Beef_Net_Test.Program"

[[ProjectFolder.Items]]
Type = "Folder"
Path = "../Common"
AutoInclude = true
